[package]
name = "jsonrpc-to-firestark"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls"] }
serde = "1.0.152"
serde_json = "1.0.93"
serde_with = "2.2.0"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
tokio = { version = "1.25.0", features = ["full"] }
url = "2.3.1"
